// Flavor text shown throughout the games. pickQuip(category) returns a random line.
import { pick } from './util.js';

export const QUIPS = {
  "elimination": [
    "has been voted off the island of trust 🕵️",
    "just got a one-way ticket to Spectatorville",
    "has left the chat... permanently 👋",
    "was sus. The people have spoken.",
    "got the boot. Democracy is brutal.",
    "is out! Cue the dramatic exit music 🎬",
    "has been un-invited from the party",
    "took the walk of shame to the bench",
    "is now on snack duty. Forever.",
    "has been yeeted by popular demand",
    "couldn't talk their way out of that one",
    "is out. The group chat has decided 📱",
    "will be remembered fondly. Probably.",
    "got caught in 4K. Case closed 📸"
  ],
  "insiderWin": [
    "Justice served! Insiders win 🎉",
    "The impostors never stood a chance!",
    "Truth wins! Somebody call the newspapers 📰",
    "Insiders: 1, Sneaky liars: 0",
    "Detective mode: activated. Case closed!",
    "The town sleeps easy tonight 🌙",
    "All impostors caught! Sherlock is proud.",
    "The lies crumbled like day-old cookies 🍪",
    "Insiders win! Never doubt the group chat.",
    "Every liar unmasked. Chef's kiss 👌",
    "The good guys win! It happens sometimes.",
    "Suspicion level: perfectly calibrated 🔍",
    "Team Honesty takes the crown 👑"
  ],
  "outsiderWin": [
    "The outsiders pulled it off 😈",
    "Deception: 1, Deduction: 0",
    "You were fooled. Beautifully.",
    "The impostors win! Trust no one.",
    "Masterclass in lying. Slow applause 👏",
    "The outsiders walked away whistling 🎶",
    "Plot twist: the liars were GOOD at lying",
    "Blend In victory! They blend in scarily well",
    "The wolves ate well tonight 🐺",
    "Straight faces, crooked hearts. They win!",
    "Espionage level: expert. GG, insiders.",
    "They lied. You bought it. The end 🎭",
    "Sneaky wins the day. Take notes, everyone."
  ],
  "whiteGuessCorrect": [
    "The Blank cracked the code! Unbelievable 🤯",
    "One wild guess. One perfect answer.",
    "Knew NOTHING and still won. Iconic 🎩",
    "That guess deserves a standing ovation",
    "Bluffed all game, nailed the finale!",
    "The Blank steals it at the buzzer!",
    "Zero clues. Total victory. Legendary.",
    "The audacity! The accuracy! 🎯",
    "The Blank read the room like a book 📖",
    "Winging it has never looked so good",
    "Correct! The Blank was listening all along 👂",
    "A snake? Yes. A genius? Also yes.",
    "Mind reader confirmed. The Blank wins!"
  ],
  "whiteGuessWrong": [
    "Swing and a miss, Blank 😅",
    "So close! Actually no, not close at all.",
    "The Blank guessed... creatively. And wrong.",
    "Nice try! The word keeps its secret.",
    "The bluff ran out of runway ✈️",
    "Wrong word! Insiders can breathe again",
    "That guess was bold. Just not correct.",
    "That crystal ball needs new batteries 🔮",
    "Confidence: 100. Accuracy: 0.",
    "Not even in the same zip code 📍",
    "Alas! The secret stays secret.",
    "The Blank gambled and the house won 🎲",
    "A for effort, F for the answer"
  ],
  "itemYes": [
    "Welcome aboard! That's coming with us 🏝️",
    "Approved! Pack it next to the coconuts 🥥",
    "Yes! The island gods are pleased",
    "That one fits! Toss it in the boat ⛵",
    "Stamped, sealed, island-approved ✅",
    "Ooh yes, that is SO island material",
    "Permission to board: granted 🫡",
    "It's in! The pattern approves.",
    "Green light! Load it up 🟢",
    "That's a keeper. The island says hi.",
    "Correct vibes detected. Come aboard!",
    "Yes! You speak the island's language",
    "The suitcase just got heavier 🧳"
  ],
  "itemNo": [
    "Hmm, the island politely declines 🙅",
    "Not this time! The boat is picky.",
    "Rejected. But with love 💛",
    "That one stays on the mainland, sorry!",
    "The pattern said 'hmm, no thanks'",
    "Denied! The island has standards, apparently",
    "Nope! But great taste otherwise.",
    "Customs took one look and said no 🛃",
    "Not quite the vibe. Try again!",
    "The island left that one on read 📵",
    "So close to the boat, yet so far ⛵",
    "That item missed the ferry. Next!",
    "Left behind, but never forgotten. Okay, forgotten."
  ],
  "patternCorrect": [
    "You cracked it! Big brain energy 🧠",
    "Pattern solved! The island bows to you",
    "Genius alert! Someone call Mensa 🚨",
    "Yes! You saw through the madness.",
    "Correct! You're basically a detective now",
    "The secret is out, brilliantly done ✨",
    "Nailed it! The island hides nothing from you",
    "Pattern: cracked. Bragging rights: earned.",
    "You connected the dots like a pro 🔗",
    "That's it! Galaxy brain confirmed 🌌",
    "Solved! And they said it couldn't be done.",
    "The pattern never stood a chance!",
    "Correct! Take a bow, mastermind 🎩"
  ],
  "patternWrong": [
    "Not quite! The island keeps its secret 🤫",
    "Good theory! Wrong island though.",
    "Close, but the pattern giggles on",
    "Nope. But that was a fun guess!",
    "The mystery lives another round 🔍",
    "Not it! Keep those brain gears turning ⚙️",
    "Wrong, but wonderfully wrong!",
    "The pattern remains undefeated. For now.",
    "Nice swing! The answer ducked.",
    "Not this time. You're circling it though!",
    "The island whispers: 'try again' 🌊",
    "Incorrect, but your confidence? Inspiring.",
    "Almost! The secret is a slippery one 🐟"
  ],
  "voteTie": [
    "It's a tie! Democracy is confused 🤷",
    "Deadlock! Nobody walks the plank... yet",
    "A perfect split! The tension is delicious",
    "Tie vote! The universe demands a recount",
    "Even steven! Everyone side-eyes everyone 👀",
    "Stalemate! Trust levels: critically low",
    "It's a draw, awkward silence intensifies",
    "Tied! Someone's poker face is working",
    "No decision! The plot thickens 🍲",
    "Split vote! Chaos reigns supreme",
    "A tie?! This town needs better gossip",
    "Nobody's out! Suspicion carries over ⏭️",
    "The scales refuse to tip ⚖️"
  ],
  "gameStart": [
    "Masks on, poker faces ready, let's go 🎭",
    "Trust no one. Suspect everyone. Have fun!",
    "New round, new lies, new legends 🌟",
    "Let the beautiful chaos begin!",
    "Somebody here is lying. Delightful!",
    "Game on! May the sneakiest win 😏",
    "Deep breaths. Sharp eyes. Go time 👁️",
    "The stage is set. The lies are loaded 🎬",
    "Round start! Friendships on pause",
    "Buckle up, deception incoming!",
    "Eyes peeled, friends. It's showtime!",
    "Let the mind games commence 🧠",
    "Pack your brain. We're going in 🧳",
    "One secret. Many suspects. Begin!"
  ]
};

export function pickQuip(category) {
  return pick(QUIPS[category] || []) || '';
}
